# Generated by Django 2.1.1 on 2019-01-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation_app', '0002_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropdata',
            name='moisture_value',
            field=models.FloatField(),
        ),
    ]
