# Generated by Django 2.1.1 on 2019-01-26 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation_app', '0003_auto_20190127_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='crop',
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
    ]
